/* ==========================================================================
   expose-globals.js
   This app builds most of its UI as HTML strings with inline
   onclick="..." / onchange="..." / oninput="..." attributes (both in
   index.html and in the template strings the page/component modules
   render). Those attributes are evaluated against `window`, but ES
   modules do NOT put their top-level declarations on `window` the way
   classic <script> files do. So every function referenced from an
   inline event-handler attribute anywhere in the app is re-exported
   here and attached to window. This is the ONLY reason this file
   exists -- it changes no behavior, it just restores the global
   lookup inline HTML handlers rely on.
   ========================================================================== */

import { closeModal, confirmModalAction, openModal } from './components/modal.js';
import { navigate, navigateBack, openBomVersionCompare, openPn, openPo, openPoVersionCompare, showPnTab, showProjectTab, stop, toggleExplorer, toggleGroup, toggleSidebar } from './components/nav-render.js';
import { approveAllBomImportRows, bomImportSelectFile, bomImportUseExample, closeBomImport, downloadBomExample, importValidatedBom, openPoBomUploader, setMaterialFilter, setMaterialSearch, toggleBomImportRow, updateBomImportCell, validateBomImportFields } from './components/shared-tables.js';
import { openGlobalSearch, setGlobalSearch, toggleNotif, toggleQA } from './components/topbar.js';
import { adminAssignProject, adminCloseReferenceForm, adminCloseUserForm, adminDeleteReferenceEntry, adminOpenReferenceForm, adminOpenUserForm, adminSaveReferenceEntry, adminSaveUser, adminSelectReferenceModule, adminSetAssignmentDraft, adminSetLoginFilter, adminSetReferenceDraft, adminSetUserDraft, adminSetUserFilter, adminToggleReferenceEntry, adminToggleUserStatus, adminUnassignProject, adminUnlockUser } from './pages/admin.js';
import { openAdminUser, openAuditDetail, resetAuditFilters, setAuditFilter, setAuditSearch } from './pages/audit.js';
import { custWizardCancel, custWizardGoStep, custWizardNext, custWizardSaveDelivery, custWizardSelectAllFgpns, custWizardSetFgpnQty, custWizardSetMethod, custWizardSetPo, custWizardSetProject, custWizardToggleFgpn, openCustDelivery, printCustomerDeliveryInstruction, recordShipmentConfirmation, resetCustFilters, setCustFilter, setCustSearch, showCustTab } from './pages/customer-delivery.js';
import { resetInvoiceFilters, setInvoiceFilter, setInvoiceSearch, setRevenueFilter } from './pages/finance.js';
import { mfgDeliveryCopyCode, mfgDeliveryPrintCode, mfgDeliveryRegenerateCode, mfgHandleSignedUpload, mfgSetDeliveryReceiver, mfgValidateDeliveryCode, mfgWizardContinueFromContext, mfgWizardContinueFromItems, mfgWizardContinueFromParts, mfgWizardGoStep, mfgWizardSaveInstruction, mfgWizardSelectAllFgpns, mfgWizardSelectAllMaterials, mfgWizardSetFgpnQty, mfgWizardSetItemTime, mfgWizardSetPo, mfgWizardSetProject, mfgWizardSetQty, mfgWizardToggleFgpn, mfgWizardToggleMaterial, openMfgDelivery, openMfgLaunchSimulation, resetMfgFilters, returnToMfgInstruction, setMfgFilter, setMfgSearch } from './pages/manufacturing-delivery.js';
import { addTransitMaterial, cancelEditThreshold, executeWipTransfer, importCutmanFile, openMaterialDetail, recordStockReception, removeTransitMaterial, restoreThresholdDefault, saveThreshold, startEditThreshold } from './pages/materials-stock.js';
import { toggleTree } from './pages/parts-bom.js';
import { poContinueUpload, poResetIntake, poSaveExtraction, poSelectFile, poSetHeaderField, poSetLineField, poSetLineSearch, poSetReviewTab, poStartExtraction, poUseExampleFile, poValidateExtraction } from './pages/po-intake.js';
import { cancelProjectForm, clearProjectBomFilters, openPoDeliveryHistory, openPoDeliveryTab, openProject, saveProjectForm, setPnFilter, setPnSearch, setProjectBomFilter, setProjectFilter, setProjectFormCustomer, setProjectSearch } from './pages/projects.js';
import { bulkPoAction, clearPoSelection, confirmPoRollback, markPackaged, markProductionDone, openAuditEvidence, openPoRollback, selectBomVersion, selectPoVersion, setBomWorkspaceCompareA, setBomWorkspaceCompareB, setPoFilter, setPoSearch, setPoWorkspaceCompareA, setPoWorkspaceCompareB, setProductionStatusFilter, setProjectOpsPo, startProjectCustomerDelivery, togglePoSelect, togglePoSelectAll } from './pages/purchase-orders.js';
import { renderPage } from './pages/router.js';
import { addSimIncomingMaterial, backFromVersionCompare, exportMissingMaterialList, generateFutureStockDraft, removeSimIncomingMaterial, runSimulation, saveMeetingMinutes, setSimBomVersion, setSimIncomingDraft, setSimMeetingMinutes, setSimMode, setSimPoVersion, setSimPriorityRule, setSimProject, setSimScope, setSimSinglePo, setVersionCompareA, setVersionCompareB, setVersionCompareSearch, swapVersionComparison, toggleSimAllPos, toggleSimPo, toggleSimSource, toggleSimUseCurrentVersions, toggleVersionCompareFilter } from './pages/simulation.js';
import { downloadOriginalPoPdf, downloadPoExtractionExcel, exportNotice, exportWorkspaceTable, refreshNotice, toggleColMenu, toggleColumn } from './utils/table-helpers.js';

Object.assign(window, {
  addSimIncomingMaterial,
  addTransitMaterial,
  adminAssignProject,
  adminCloseUserForm,
  adminCloseReferenceForm,
  adminDeleteReferenceEntry,
  adminOpenReferenceForm,
  adminOpenUserForm,
  adminSaveReferenceEntry,
  adminSaveUser,
  adminSelectReferenceModule,
  adminSetAssignmentDraft,
  adminSetLoginFilter,
  adminSetReferenceDraft,
  adminSetUserDraft,
  adminSetUserFilter,
  adminToggleReferenceEntry,
  adminToggleUserStatus,
  adminUnassignProject,
  adminUnlockUser,
  approveAllBomImportRows,
  backFromVersionCompare,
  bomImportSelectFile,
  bomImportUseExample,
  bulkPoAction,
  cancelEditThreshold,
  cancelProjectForm,
  clearPoSelection,
  clearProjectBomFilters,
  closeBomImport,
  closeModal,
  confirmModalAction,
  confirmPoRollback,
  custWizardCancel,
  custWizardGoStep,
  custWizardNext,
  custWizardSaveDelivery,
  custWizardSelectAllFgpns,
  custWizardSetFgpnQty,
  custWizardSetMethod,
  custWizardSetPo,
  custWizardSetProject,
  custWizardToggleFgpn,
  downloadBomExample,
  downloadOriginalPoPdf,
  downloadPoExtractionExcel,
  executeWipTransfer,
  exportMissingMaterialList,
  exportNotice,
  exportWorkspaceTable,
  generateFutureStockDraft,
  importCutmanFile,
  importValidatedBom,
  markPackaged,
  markProductionDone,
  mfgDeliveryCopyCode,
  mfgDeliveryPrintCode,
  mfgDeliveryRegenerateCode,
  mfgHandleSignedUpload,
  mfgSetDeliveryReceiver,
  mfgValidateDeliveryCode,
  mfgWizardContinueFromContext,
  mfgWizardContinueFromItems,
  mfgWizardContinueFromParts,
  mfgWizardGoStep,
  mfgWizardSaveInstruction,
  mfgWizardSelectAllFgpns,
  mfgWizardSelectAllMaterials,
  mfgWizardSetFgpnQty,
  mfgWizardSetItemTime,
  mfgWizardSetPo,
  mfgWizardSetProject,
  mfgWizardSetQty,
  mfgWizardToggleFgpn,
  mfgWizardToggleMaterial,
  navigate,
  navigateBack,
  openAdminUser,
  openAuditDetail,
  openAuditEvidence,
  openBomVersionCompare,
  openCustDelivery,
  openGlobalSearch,
  openMaterialDetail,
  openMfgDelivery,
  openMfgLaunchSimulation,
  openModal,
  openPn,
  openPo,
  openPoBomUploader,
  openPoDeliveryHistory,
  openPoDeliveryTab,
  openPoRollback,
  openPoVersionCompare,
  openProject,
  poContinueUpload,
  poResetIntake,
  poSaveExtraction,
  poSelectFile,
  poSetHeaderField,
  poSetLineField,
  poSetLineSearch,
  poSetReviewTab,
  poStartExtraction,
  poUseExampleFile,
  poValidateExtraction,
  printCustomerDeliveryInstruction,
  recordShipmentConfirmation,
  recordStockReception,
  refreshNotice,
  removeSimIncomingMaterial,
  removeTransitMaterial,
  renderPage,
  resetAuditFilters,
  resetCustFilters,
  resetInvoiceFilters,
  resetMfgFilters,
  restoreThresholdDefault,
  returnToMfgInstruction,
  runSimulation,
  saveMeetingMinutes,
  saveProjectForm,
  saveThreshold,
  selectBomVersion,
  selectPoVersion,
  setAuditFilter,
  setAuditSearch,
  setBomWorkspaceCompareA,
  setBomWorkspaceCompareB,
  setCustFilter,
  setCustSearch,
  setGlobalSearch,
  setInvoiceFilter,
  setInvoiceSearch,
  setMaterialFilter,
  setMaterialSearch,
  setMfgFilter,
  setMfgSearch,
  setPnFilter,
  setPnSearch,
  setPoFilter,
  setPoSearch,
  setPoWorkspaceCompareA,
  setPoWorkspaceCompareB,
  setProductionStatusFilter,
  setProjectBomFilter,
  setProjectFilter,
  setProjectFormCustomer,
  setProjectOpsPo,
  setProjectSearch,
  setRevenueFilter,
  setSimBomVersion,
  setSimIncomingDraft,
  setSimMeetingMinutes,
  setSimMode,
  setSimPoVersion,
  setSimPriorityRule,
  setSimProject,
  setSimScope,
  setSimSinglePo,
  setVersionCompareA,
  setVersionCompareB,
  setVersionCompareSearch,
  showCustTab,
  showPnTab,
  showProjectTab,
  startEditThreshold,
  startProjectCustomerDelivery,
  stop,
  swapVersionComparison,
  toggleBomImportRow,
  toggleColMenu,
  toggleColumn,
  toggleExplorer,
  toggleGroup,
  toggleNotif,
  togglePoSelect,
  togglePoSelectAll,
  toggleQA,
  toggleSidebar,
  toggleSimAllPos,
  toggleSimPo,
  toggleSimSource,
  toggleSimUseCurrentVersions,
  toggleTree,
  toggleVersionCompareFilter,
  updateBomImportCell,
  validateBomImportFields,
});
